### ISSUE TITLE
Update React Dependency

### ISSUE THREAD

**Issue by TigerC10** [andreypopp/react-textarea-autosize#102]
Per https://facebook.github.io/react/blog/2016/02/19/new-versioning-scheme.html - React has updated their versioning, https://facebook.github.io/react/blog/2016/04/07/react-v15.html

As such, react-textarea-autosize should start looking to update its dependency on react in `package.json`.

```plain
├── UNMET PEER DEPENDENCY react@15.0.2
└── react-textarea-autosize@3.3.1

npm WARN EPEERINVALID react-textarea-autosize@3.3.1 requires a peer of react@^0.14.0 but none was installed.
```

**Comment by andreypopp** [comment]
Use `react-textarea-autosize@^4.0.0`

**Comment by TigerC10** [comment]
Weird, when I do `npm install react-textarea-autosize` it installs 3.3.1.  Forcing the version number in the package.json fixed it.

**Comment by andreypopp** [comment]
If you have version specified in `package.json` then I believe npm would conform to it when running `npm install` in a package dir.

**Comment by TigerC10** [comment]
Yeah, except it wasn't in package.json or in node_modules dir.  Not sure what was going on, maybe my NPM cache was out of date or something...
