### ISSUE TITLE
NPM version of the plugin isn't right

### ISSUE THREAD

**Issue by happy-dev** [andreypopp/react-textarea-autosize#111]
I couldn't really say in details what's wrong with the NPM version, but it seems an output from Babel, and thus it can't be imported in a React Native project. It should probably be updated to match this repo.

I joined the zip version so you can check : [react-textarea-autosize.zip](https://github.com/andreypopp/react-textarea-autosize/files/365666/react-textarea-autosize.zip)

**Comment by andreypopp** [comment]
This component won't work with React Native as it depends on DOM.

**Comment by happy-dev** [comment]
My bad, I wasn't careful enough enough. 
Sorry
