### ISSUE TITLE
Unknown props warning with react 15.2.1

### ISSUE THREAD

**Issue by afhole** [andreypopp/react-textarea-autosize#112]
The non-standard attributes on the `textarea` generate warnings in React 15.2.1

```
Warning: Unknown props `minRows`, `onHeightChange`, `useCacheForDOMMeasurements` on <textarea> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
in textarea (created by TextareaAutosize)
```

Advice in React docs is to use custom attributes:

> You are using a non-standard DOM attribute on a native DOM node, perhaps to represent custom data. If you are trying to attach custom data to a standard DOM element, consider using a custom data attribute as described on MDN.

**Comment by dashed** [comment]
For posterity, this warning persists in react v15.3.1.

**Comment by Andarist** [comment]
Issue should be fixed for quite some time, if not - let me know and Im gonna reopen
