### ISSUE TITLE
 Cannot read property 'getAttribute' of null

### ISSUE THREAD

**Issue by madshargreave** [andreypopp/react-textarea-autosize#114]
Hi

I get the following error if I refresh the browser on a page where the component will mount.

```
Cannot read property 'getAttribute' of null 

calculateNodeStyling  @ calculateNodeHeight.js:82
calculateNodeHeight @ calculateNodeHeight.js:31
_resizeComponent  @ TextareaAutosize.js:146
```

However, if I navigate to the page through for example React Router, it works fine

**Comment by madshargreave** [comment]
A hacky, temporary solution is do something like

```
componentWillMount () {
    setTimeout(() => this.setState({ show: true }), 0)
  }

render () {
    if (!this.state.show) { return null }
    ...
````

Which suggests that the problem has something to do with ReactTextareaAutosize's rootnode not being available in the first render-cycle.

**Comment by jdalton** [comment]
Hi @madshargreave!

I can't repro this.
