### ISSUE TITLE
Active maintainers needed

### ISSUE THREAD

**Issue by andreypopp** [andreypopp/react-textarea-autosize#115]
It became obvious that I have no time now to properly maintain the project. I added few people (@KyleAMathews and @nikgraf) to contributors a while back but it looks like they don't have time either or not interested.

Therefore I'm calling for new maintainers for the project. CC'ing people who might be interested: @vinnymac @necolas @slorber @dashed

**Comment by Keats** [comment]
How about joining forces with [react-autosize-textarea](https://github.com/buildo/react-autosize-textarea)?
I'm currently using that and it works very well and both libraries have the same goals

**Comment by jdalton** [comment]
Hey @andreypopp! I :heart: to help out!

**Comment by dashed** [comment]
I nominate @jdalton as the next benevolent maintainer for life (BMFL) 😄 .

**Comment by andreypopp** [comment]
@jdalton awesome, just added you to a repo as a collaborator

**Comment by andreypopp** [comment]
@jdalton let me know your npm username

**Comment by jdalton** [comment]
:metal: My username is [jdalton](https://www.npmjs.com/~jdalton) :)

**Comment by andreypopp** [comment]
@jdalton yeah, that was just to confirm :-) added you, hooray open source 🎉

**Comment by KyleAMathews** [comment]
Thanks @jdalton!

**Comment by Andarist** [comment]
@andreypopp @jdalton I would love to help out a little bit too, mainly maintaining stuff only - migrations for newer versions of react, merging PRs etc. No time to develop this actively though.
