### ISSUE TITLE
Unable to build example.

### ISSUE THREAD

**Issue by jdalton** [andreypopp/react-textarea-autosize#117]
After `npm i` and `make` in the root and then going to `/example` and `npm i` and
`make build` I get an error:
```js
ReferenceError: [BABEL] /Users/me/Projects/react-textarea-autosize/example/index.js: Unknown option: /Users/me/Projects/react-textarea-autosize/.babelrc.presets while parsing file: /Users/me/Projects/react-textarea-autosize/example/index.js
```
The `babel-preset-prometheusresearch` is installed.

**Comment by andreypopp** [comment]
Looks like the example is pinned to babel 5.

**Comment by jdalton** [comment]
Ah yeah, I was doing research into the error and that came up.

**Comment by jdalton** [comment]
Fix incoming...
