### ISSUE TITLE
Incorrect resize behaviour with controlled component

### ISSUE THREAD

**Issue by rhys-vdw** [andreypopp/react-textarea-autosize#121]
### Problem

In a controlled component, it seems the height is initially determined _before_ the `value` prop is updated.

I have a component that strips newlines from entered text. Simplification of my logic:

``` jsx
export function simplifyWhitespace(string) {
  return string.replace(/\s+/g, ' ')
}

class Example extends Component {
  constructor(props) {
    super(props)
    this.state = { text: '' }
    this.handleTextChange = this.handleTextChange.bind(this)
  }

  handleTextChange(event) {
    this.setState({ text: simplifyWhitespace(event.target.value) })
  }

  render() {
    return (
      <Textarea
        value={this.state.text}
        onChange={this.handleTextChange}
      />
    )
  }
}
```

Problematic behaviour when tapping enter:

![bad-autosize](https://cloud.githubusercontent.com/assets/822105/19586893/8fd16c30-97a5-11e6-9e74-993688f8787c.gif)
## Cause

It seems to me that the [resize code being called in the `textarea`'s `onChange` callback](https://github.com/andreypopp/react-textarea-autosize/blob/25e22fd70fa5e9ecac55cbdabab23e7010bda1d3/src/TextareaAutosize.js#L139-L140) makes sense only for an uncontrolled component. It assumes that [new size will be based on the current `value` attribute of the element](https://github.com/andreypopp/react-textarea-autosize/blob/25e22fd70fa5e9ecac55cbdabab23e7010bda1d3/src/calculateNodeHeight.js#L57), which is not true for an uncontrolled component.
## Possible solution

The `calculateNodeStyle` function should also take a string containing the next `value` (since this cannot be assumed to be the current `value` of the element). For a controlled component, I think this logic might be added to the `componentWillReceiveProps`.

Perhaps something like:

``` js
_resizeComponent(value) {
  // directly modify element stye in DOM
  Object.assign(
    this.textareaElement.style,
    calculateNodeStyle(value, /* other args... */)
  )
}

componentWillReceiveProps(nextProps) {
  // If this is a controlled component (ie. `value` is set, and has changed), then resize:
  if (this.props.value !== nextProps.value) {
    this._resizeComponent(nextProps.value)
  }
}

_onChange(event) {
  // An uncontrolled component will update each time its content changes:
  if (this.props.value == null) {
    this._resizeComponent(event.target.value)
  }
}
```

Happy to provide a PR to address this. If my understanding is correct it should be fairly straight forward.

**Comment by Andarist** [comment]
I think your use case got fixed with recent changes and fixes. Going to close this, but if you can confirm that it's working it would be great.

Also if you want to propose better implementation than what has been done in the library - please send a PR so we can discuss more.
