### ISSUE TITLE
Won't resize when inherited font size changes

### ISSUE THREAD

**Issue by felipeochoa** [andreypopp/react-textarea-autosize#122]
I have a component where users can select font sizes which are set on the parent's style as `{fontSize: <computed>}`. Unfortunately, changing the parent's font size does not trigger an update and resize in the child. 

Before resizing:
<img width="157" alt="capture" src="https://cloud.githubusercontent.com/assets/2739312/19762526/9ec0fc80-9c3a-11e6-894d-cb1237eeaebb.PNG">

After resizing:
<img width="211" alt="capture" src="https://cloud.githubusercontent.com/assets/2739312/19762553/b5844db4-9c3a-11e6-9e68-ff454d1bdfe2.PNG">

I think handling this type of situation requires forcing an update of the component, but there's no public method for doing so. A related problem is when other elements expand or shrink and cause the textarea dimensions to change. (I think handling the general case would require something like [this](https://github.com/wnr/element-resize-detector) to detect resize events)

**Comment by Andarist** [comment]
Hey, we cannot use `element-resize-detector` as it creates quite an overhead. Possible solutions are as follow:
- you could trigger pass 'invalidating' prop (such as fontSize) to the Textarea component - it should recalculate itself
- or we could expose imperative `resize` method on the component which you could access from its ref

Did you eventually fix your issue?

**Comment by felipeochoa** [comment]
Rolled my own using http://www.jacklmoore.com/autosize/. You can see it at this gist: https://gist.github.com/felipeochoa/1ada203ea68dce134d920b170bdd13cc
