### ISSUE TITLE
IE11: Placeholder of the textarea will only show up after focus and blur

### ISSUE THREAD

**Issue by kukikiloke** [andreypopp/react-textarea-autosize#125]
The textarea does not display the placeholder on initial load. However if you focus on the textarea and blur it (e.g. click outside the textarea) the placeholder will appear.

Code snippet:
```
<Textarea
	value={this.state.commentDraft}
	placeholder="Write a comment..."
	style={{ fontSize: 'small', maxHeight: '250px', resize: 'none' }}
	onChange={e => this.setState({ commentDraft: e.target.value })} />
```

OS: Windows 10
Browser: IE 11

**Comment by pratiko7** [comment]
+1 ^ Any resolutions for this?

**Comment by MrFlof** [comment]
Are you guys on an updated version of React?  This library has absolutely nothing to do with the placeholder text not showing up.

This was a React issue with IE 11.  It was patched May 24th https://github.com/facebook/react/pull/6406 .

**Comment by Andarist** [comment]
If that was React's fault and it got fixed then I'm gonna close this issue.

**Comment by johnmeng24** [comment]
upgrade  react-dom version at least  15.4.2
