### ISSUE TITLE
how to set default height

### ISSUE THREAD

**Issue by craigcosmo** [andreypopp/react-textarea-autosize#126]
When component mounted, I want the textarea to be 32px height. 

I tried this

```jsx
<Textarea style={{height:'32px'}}></Textarea>
```

and this

```jsx
<Textarea style={{height:'32'}}></Textarea>
```

Both does not work. Inspect the element in chrome, it shows the height is hard code inline with value is 29px

**Comment by taylormsj** [comment]
```
props.style = {
      ...props.style,
      height: this.state.height || 0,
    };
```
might suggest that what you're trying to do isn't supported

**Comment by craigcosmo** [comment]
@taylormsj so how you set default height?

**Comment by diessica** [comment]
Did you try setting `min-height`?

**Comment by craigcosmo** [comment]
min-height works.
