### ISSUE TITLE
Change textarea height and value from parent component

### ISSUE THREAD

**Issue by max-mykhailenko** [andreypopp/react-textarea-autosize#13]
Please, add example for this.

**Comment by andreypopp** [comment]
Value can be updated by rendering component with a `value` prop: `<Textarea value="somenewvalue" />`. Height of the component is computed based on the current value. If you want to set your own height, just use `<textarea />` DOM component.

**Comment by max-mykhailenko** [comment]
If I set value to empty string your component doesn't change size

**Comment by andreypopp** [comment]
That's a bug.

**Comment by max-mykhailenko** [comment]
I create pull request with possible solution
