### ISSUE TITLE
What files need to be hosted?

### ISSUE THREAD

**Issue by sufuf3** [andreypopp/react-textarea-autosize#132]
Hi @andreypopp, 
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs). We want to host this library.
Now I guess the files need to be added in cdnjs as fllowing:

- src/TextareaAutosize.js
- src/calculateNodeHeight.js

Could you please confirm if there is any other files need to be added in cdnjs?
Thank you.

[cdnjs/cdnjs#10364](https://github.com/cdnjs/cdnjs/pull/10364)

**Comment by Andarist** [comment]
Closing this as duplicate of #140
