### ISSUE TITLE
Warning: Unknown prop `inputRef` on <textarea> tag. Remove this prop from the element.

### ISSUE THREAD

**Issue by briska** [andreypopp/react-textarea-autosize#133]
Here: https://github.com/andreypopp/react-textarea-autosize/blob/master/src/TextareaAutosize.js#L102 you pass {...props} to <textarea>, which includes inputRef prop, so React throws this warning... could you please fix this? thanks :)

**Comment by himynameisdave** [comment]
It's been added here: https://github.com/andreypopp/react-textarea-autosize/pull/123

But unfortunately the new release has not been published to NPM yet 👎 

---

@jdalton @andreypopp can you guys please release/publish this fix? Thanks 😃

**Comment by briska** [comment]
yes, i see it's not on NPM yet, but i downloaded actual code from here and it throws this warning... you can't pass inputRef to <textarea> tag (through {...props}), because it's unknown prop for this tag - in render method, you need to destructure inputRef from this.props, so it's not in props, that you pass to <textarea>... like this:

```
let {
      valueLink,
      minRows: _minRows,
      maxRows: _maxRows,
      onHeightChange: _onHeightChange,
      useCacheForDOMMeasurements: _useCacheForDOMMeasurements,
      inputRef, 
      ...props,
    } = this.props;
```

**Comment by jdalton** [comment]
Closing as this has been patched by #123. While I have publish rights my roll was more of repo sitting, until another could be found. I'm not super familiar with this project so I'm hoping another can take up the mantle (maybe @himynameisdave or @hosmelq). If so could you all prep a PR that version bumps and sanity checks this release. I'll merge that in the short term until proper commit rights can be extended by @andreypopp.

**Comment by hosmelq** [comment]
I'll send a PR this night

**Comment by andreypopp** [comment]
Let me know whom needs commit access to the repo. I also can transfer repo to some org so that I don't serve as a single point of failure.
