### ISSUE TITLE
word-break parameter not handled when calculating height

### ISSUE THREAD

**Issue by Bucky24** [andreypopp/react-textarea-autosize#137]
In the case when nothing but spaces are put into the textarea, then the enter key is pressed, in some browsers this will cause scrollbars to show up. This can be fixed by adding word-break: breakall to the textarea, however this is not taken into account when calculating the height of the textarea, causing a scrollbar to show up anyway.

**Comment by olofssonanton** [comment]
I, too, am experiencing scrollbars showing up, whilst running Chrome 57. Cannot get it to happen on Firefox 52. Certain line amounts consistently show vertical scrollbars, and simply adding one extra pixel to the height hides them.

**Comment by Andarist** [comment]
could u post reproduced issue on something like codesandbox.io?

**Comment by Andarist** [comment]
The issue got stale and author has not shared detailed info about the problem. Closing the issue, feel free to respond back at any time.
