### ISSUE TITLE
Could this library distribute a single file?

### ISSUE THREAD

**Issue by sufuf3** [andreypopp/react-textarea-autosize#140]
Hi, 
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs). We want to host this library.

Both of `src/TextareaAutosize.js` and `src/calculateNodeHeight.js` should component to work. (ref: https://github.com/cdnjs/cdnjs/pull/10364#issuecomment-290110517)
But this library isn't distributed a single file, would you like to provide it?

If you have any suggestions, please let me know.

Thank you.

#132
cdnjs/cdnjs#10364

**Comment by Andarist** [comment]
We gonna provide it in the nearest future, there is a pending PR for this. After releasing should something more be done on our side so you can host this? Like informing u somewhere?

**Comment by sufuf3** [comment]
@Andarist It sounds good. Thank you very much.
If it does not bother you, please let me know here --> cdnjs/cdnjs#10364
I'll host this library after you release.

**Comment by Andarist** [comment]
closing this in favor of the PR on `cdnjs` repo
