### ISSUE TITLE
PropTypes package deprecation warning

### ISSUE THREAD

**Issue by aaronmcadam** [andreypopp/react-textarea-autosize#143]
With React 15.5, we now see the following console warning:

`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

Here's an example of how `enzyme` migrated: https://github.com/airbnb/enzyme/pull/876

**Comment by th3fallen** [comment]
+1

**Comment by marlonbernardes** [comment]
+1

**Comment by marlonbernardes** [comment]
Apparently the PR #141 fixes this issue. @andreypopp any chance we could get it merged? Thanks! :)

**Comment by MadTiago** [comment]
+1

**Comment by Andarist** [comment]
I've released updated version. Please let me know if everything is working as expected.
