### ISSUE TITLE
Linux Chromium zoom scrollbar bug

### ISSUE THREAD

**Issue by kengho** [andreypopp/react-textarea-autosize#147]
Hello.

In current stable Chromium on Linux (`chromium-browser/xenial-updates,xenial-security,now 57.0.2987.98-0ubuntu0.16.04.1276 amd64`) when you zoom page to 200% scrollbar appears on `<TextareaAutosize />`.

Steps to reproduce:
1. Install fresh Ubuntu 16.04.02 / Mint 18.1 / etc
2. `sudo apt-get install chromium-browser`
3. goto [https://andreypopp.github.io/react-textarea-autosize/](https://andreypopp.github.io/react-textarea-autosize/)
4. scroll page to the bottom
5. zoom to 200%

After adding 1px to textarea'a height in page inspector scrollbar disappears.

Spotted only in Chomium@Linux, while Firefox@Linux, Firefox@Windows and Chromium@Windows works fine.

I don't sure it's react-textarea-autosize's bug, but maybe we could add some workaround until Chromium fixes it? Adding 1px to textarea's height should do the trick, or at least adding corresponding hook for developer to add this 1px manually in case chromium useragent appears.

![react-textarea-autosize-chromium-bug-0](https://cloud.githubusercontent.com/assets/7105231/25304511/753bab86-2771-11e7-872e-9d0fbec644be.png)
![react-textarea-autosize-chromium-bug-1](https://cloud.githubusercontent.com/assets/7105231/25304512/753bd1e2-2771-11e7-996c-2fb7b2b4d093.png)

**Comment by Andarist** [comment]
Are u sure that the scroll should appear in ur use scenario? You describe that it is caused by adding 1px to the height and propose fixing this by adding 1px, is this correct? Wouldnt like to include such dirty hacks in the library - if you want to tackle this on ur side isnt `onHeightChange` enough to handle this?

**Comment by kengho** [comment]
You're right, something like this fixes the bug.

```
<TextareaAutosize
  inputRef={(c) => { this.textareaInput = c; }}
  onHeightChange={() => {
    const currentHeightPx = this.textareaInput.style.height;
    const currentHeight = Number(currentHeightPx.slice(0, currentHeightPx.length - 2));
    this.textareaInput.style.height = `${currentHeight + 1}px`;
  }}
/>
```

Thanks for advice.
