### ISSUE TITLE
Run a function after component has mounted...

### ISSUE THREAD

**Issue by joetidee** [andreypopp/react-textarea-autosize#148]
Is there a way to run a custom function after the `<TextareaAutosize />` component has mounted?

**Comment by Andarist** [comment]
Not rly - you can check the source code [here](https://github.com/andreypopp/react-textarea-autosize/blob/master/src/TextareaAutosize.js#L110-L113). What's ur use case for such a functionality?

**Comment by joetidee** [comment]
Thanks for getintg back. Mananged to solve my use case using the built-in 'on height change' handler.
