### ISSUE TITLE
Latest patch breaks server side rendering.

### ISSUE THREAD

**Issue by main-kun** [andreypopp/react-textarea-autosize#152]
In the latest patch there are `document` and `window` calls. This makes the library impossible to use with SSR.

**Comment by Andarist** [comment]
Eh, sorry for that - forgot about SSR support on this one. Gonna fix in half an hour.

**Comment by Andarist** [comment]
@main-kun please check now. Everything should be alright once again. Sorry for regression.

**Comment by main-kun** [comment]
Yeah, everything is fine now. Thank you.

**Comment by Andarist** [comment]
Thanks for the confirmation! I hope the broken version didnt get deployed anywhere to the production.
