### ISSUE TITLE
getComputedStyle returns null in iframe in Firefox

### ISSUE THREAD

**Issue by TLadd** [andreypopp/react-textarea-autosize#153]
If we try to render a <TextareaAutosize /> within an iframe with display: none, calculateNodeHeight throws an exception in Firefox because of this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=548397. calculateNodeHeight returns null under these circumstances and https://github.com/andreypopp/react-textarea-autosize/blob/master/src/calculateNodeHeight.js#L13 throws an error.

I am using v4.3.2
Firefox v53.0.2

**Comment by Andarist** [comment]
Reproduced issue - https://jsfiddle.net/rfesgey1/1/

What's ur use case of rendering such iframe. Do you set its display later to something different than `display: none;`?

**Comment by TLadd** [comment]
Yeah, so in our situation, the iframe is initially `display: none` and then changes to `display: block`

We are rendering an embeddable chat widget in the iframe. On page load, the iframe is `display: none`. From within the iframe, we are requesting some data that is necessary for rendering the widget. When this data loads, we send a postmessage outside the iframe to signal that we are rendering, at which point display is set to 'block'

**Comment by Andarist** [comment]
Gonna handle this one by the end of the weekend, im planning to release v5 (minor, but breaking changes) of the lib which should fix this. In most cases this will be a drop-in replacement for the old one.

**Comment by Andarist** [comment]
So I've released v5, u can install it using `npm install --save react-textarea-autosize@next`.

This should fix ur issue, i have not yet tested it properly - if u want to help with that I would appreciate it. Anyway - I will test it in following week in production and release later as `latest`.

**Comment by TLadd** [comment]
Pulled in 5.0.1 and [the remaining call](https://github.com/andreypopp/react-textarea-autosize/blob/master/src/calculateNodeHeight.js#L119) to getComputedStyle still results in getting an error in this case.

**Comment by Andarist** [comment]
Thanks for checking this out, gonna tackle this today and release the fix

**Comment by Andarist** [comment]
@TLadd should be fixed in `5.0.2`, please let me know if that helped

**Comment by TLadd** [comment]
Yep, renders fine now. Thanks!

**Comment by Andarist** [comment]
Released as `latest` :)
