### ISSUE TITLE
Assertion of `_rootDOMNode` doesn't catch `null`

### ISSUE THREAD

**Issue by kevinehosford** [andreypopp/react-textarea-autosize#157]
I see the following issue testing components that rely on `react-textarea-autosize`:
```
    TypeError: Cannot read property 'style' of null

      at Window.getComputedStyle (node_modules/jsdom/lib/jsdom/browser/Window.js:371:19)
      at calculateNodeStyling (node_modules/react-textarea-autosize/lib/calculateNodeHeight.js:111:22)
      at calculateNodeHeight (node_modules/react-textarea-autosize/lib/calculateNodeHeight.js:43:21)
      at TextareaAutosize._this._resizeComponent (node_modules/react-textarea-autosize/lib/index.js:78:58)
      at TextareaAutosize.componentDidMount (node_modules/react-textarea-autosize/lib/index.js:140:10)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:265:25
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:11
      at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:76:22)
      at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:26)
```

It seems like the following check should handle `null`: https://github.com/andreypopp/react-textarea-autosize/blob/master/src/index.js#L134

**Comment by Andarist** [comment]
What version of the library do u use?

**Comment by kevinhos** [comment]
v5.0.6

**Comment by Andarist** [comment]
Could u share repository with reproduced issue? It would certainly speed up the fix for this.

**Comment by Andarist** [comment]
@kevinhos any updates on this?

**Comment by kevinhos** [comment]
I apologize. I've been struggling to find time to put together an example.

**Comment by savovs** [comment]
Works fine for me on 4.0.5, when I tried upgrading I got this error:
`"TypeError: Cannot read property 'getHostNode' of null"`

When doing this:

```javascript
<Textarea
							className={error ? 'alert' : ''}
							value={value}
							onChange={onChange}
							type={type}
							name={field}
							placeholder={placeholder}
							ref={componentReference => this._input = componentReference}
						/>
```

**Comment by Andarist** [comment]
@savovs could u reproduce on something like codesandbox.io ?

**Comment by dimon85** [comment]
@Andarist Hi, I have the same issue, when testing with jest (add snapshot)
v. 5.1.0
`  it('Should render Textarea correctly', () => {
    const tree = renderer.create(
      <Textarea
        name="description"
        placeholder="Description"
      />
    ).toJSON();

    expect(tree).toMatchSnapshot();
  });`
Get the same error `TypeError: Cannot read property 'style' of null`,
Other tests pass well.

**Comment by Andarist** [comment]
@dimon85 could u share a repository with reproduced issue and minimal setup?

**Comment by dimon85** [comment]
I an working in private repository, i need more time to create new repository.

**Comment by Andarist** [comment]
Sure thing, if I find some time I might do that myself, but lately I'm really busy and that's why I'm asking for a little bit of help here :)

**Comment by dimon85** [comment]
@Andarist  Hi, take a look this repo https://github.com/dimon85/textarea-test
Thanks.

**Comment by Andarist** [comment]
@dimon85 

I've found the solution [here](https://github.com/facebook/react/issues/7740#issuecomment-247335106).
```js
    const tree = renderer.create(
      <Textarea
        name="description"
        placeholder="Description"
      />,
      { createNodeMock: () => document.createElement('textarea') }
    ).toJSON();
```
Im not convinced at the moment that we should guard against this. `react-test-renderer` chose not to provide `ref`s automatically, its their API and people should be aware if they chose to use it. OTOH it's really a shame that this doesnt work out of the box so I might consider adding guards in the future.

Also - please use just `enzyme`, its quite a [recommended way](https://facebook.github.io/react/docs/test-utils.html#overview).

**Comment by Andarist** [comment]
@savovs @kevinhos Was your setup the same? jest + react-test-renderer?

**Comment by mertkahyaoglu** [comment]
@Andarist I'm using jest and react-test-renderer. I got the same error trying to write a snapshot test.
