### ISSUE TITLE
use mentions

### ISSUE THREAD

**Issue by raminious** [andreypopp/react-textarea-autosize#162]
Hello!
Is there a way to use 3rd party modules like https://github.com/effektif/react-mentions without manipulating codes? 
or I should fork this repo and apply my changes ?

Thank you

**Comment by Andarist** [comment]
Hi. From what I see [effektif/react-mentions](https://github.com/effektif/react-mentions) doesnt support using custom components, nor do we. 

If you to propose an implementation on our side how could we support it, im all ears.

**Comment by raminious** [comment]
Thanks sir. currently I'm playing with these two modules. I will ping you here if I could find a way.
