### ISSUE TITLE
submit in a form

### ISSUE THREAD

**Issue by dmr** [andreypopp/react-textarea-autosize#163]
I have an issue with <TextareaAutosize /> inside a form:

If a user enters a return the form gets submitted.

If I just use the normal <textarea /> the behavior is as I expected: the form is not submitted.
I haven't tracked down the issue entirely but I was wondering if some body else also experienced this and has a solution. If nobody did then I'll wrap up a small code example.

**Comment by Andarist** [comment]
Could u provide a reproduced example on something like https://codesandbox.io/ ?

**Comment by Andarist** [comment]
The issue got stale and author has not shared detailed info about the problem. Closing the issue, feel free to respond back at any time.

**Comment by dmr** [comment]
@Andarist sorry I did not provide a better explanation. I think the issue was/is somewhere in wrapper components --> Thank you for cleaning up stale issues :)
