### ISSUE TITLE
hiddenTextArea in calculateNodeHeight can be false

### ISSUE THREAD

**Issue by ablamunits** [andreypopp/react-textarea-autosize#165]
in `calculateNodeHeight`, hiddenTextarea can be false if not running in browser context, in the following line:

`const hiddenTextarea = isBrowser && document.createElement('textarea');`

This can cause tests that depend on the module to fail when accessing undefined style property further in the function, within the `forEach` loop:

```
  Object.keys(sizingStyle).forEach(key => {
    hiddenTextarea.style[key] = sizingStyle[key];
  });
```

I have created a pull request to address this issue (#164)

**Comment by Andarist** [comment]
Closing because it seems it's fixed. More can be read [here](https://github.com/andreypopp/react-textarea-autosize/pull/164#issuecomment-402148731)
