### ISSUE TITLE
How to get element with 'ref'

### ISSUE THREAD

**Issue by Tomekmularczyk** [andreypopp/react-textarea-autosize#166]
This doesn't seems to work:

                <TextareaAutosize
                    minRows={3}
                    ref={textarea => this.textarea = textarea}
                    {...rest}/>

I would like to have reference to DOM node.

**Comment by Andarist** [comment]
It depends on what kind of ref you would like to get. This should work, but will give you a ref of `TextareaAutosize` instance. If you need access to the underlying DOM element please use `inputRef={textarea => this.textarea = textarea}`
