### ISSUE TITLE
Failed propType warning in v5.0.7

### ISSUE THREAD

**Issue by cuongluu8** [andreypopp/react-textarea-autosize#167]
I'm still getting the following warning in the console
```
Warning: Failed propType: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them.
```

I'm using react 0.14.7

**Comment by cuongluu8** [comment]
if I roll back to version 3.3.1 (before the `prop-types` dependency was added) this warning goes away.
This means the latest 5.x version is no longer compatible with v0.14.7?

**Comment by Andarist** [comment]
You are trying to call one of the PropTypes validators - `typeof PropTypes.string === 'function'`, but they are not supposed to be executed by you, but by a library. You need to check your code, the easiest way to do so would be just to put a breakpoint in the place of the warning and just trace back the actual function call which has caused it.

**Comment by cuongluu8** [comment]
Done that - I'm pretty sure I am not doing that

**Comment by Andarist** [comment]
Could u share ur code on something like codesandbox.io then?

**Comment by cuongluu8** [comment]
https://codesandbox.io/s/qxq8G1Gp
Inspect the console for the error/warning

**Comment by Andarist** [comment]
Thanks for sharing, from what I see you should upgrade ur React version to v0.14.9 . More can be read here - https://github.com/facebook/prop-types/pull/26

**Comment by cuongluu8** [comment]
Yep - we'll probably upgrade to v15 in the future, but unfortunately we're stuck on 0.14.7 at the moment.

**Comment by Andarist** [comment]
In the meantime u can try to upgrade to `v0.14.9`, it shouldnt bring any breaking changes and it will get rid of those warnings.
