### ISSUE TITLE
Whitespaces doesn't expand textarea

### ISSUE THREAD

**Issue by kengho** [andreypopp/react-textarea-autosize#178]
**Steps to reproduce:**
1) open [https://andreypopp.github.io/react-textarea-autosize/](https://andreypopp.github.io/react-textarea-autosize/)
2) start spamming spaces to any textarea

**Expected results:**
Textarea's height increases as you type more spaces.

**Actual results:**
Cursor disappears, nothing else happens.

I was able to track it down to textarea's actual height measurement at [calculateNodeHeight.js#L79](https://github.com/andreypopp/react-textarea-autosize/blob/master/src/calculateNodeHeight.js#L79) just to find out that no matter what `white-space` value have `hiddenTextarea`, it's `scrollHeight` doesnt affected by trailing whitespaces. That's all I've got so far.

**Comment by Andarist** [comment]
Does it differ from the plain in-browser textareas? I remember they behave quite inconsistently in the browsers regarding the white spaces - maybe this is not library's case but the browser's? Could you create a jsfiddle with your expected results achieved with just textarea?

**Comment by kengho** [comment]
I couldn't find a way to break overflowing trailing whitespace to newline without messing with textarea's value, and I guess the lib shouldn't do that. For now I believe there are no easy good solution. But maybe someone will pull out some clever trick (if the issue worth it).

**Comment by chuntley** [comment]
@Andarist, on Chrome you can recreate the issue with the spacebar and the area where you write your Github comment. It seems that this is how browsers handle textareas by default.

**Comment by Andarist** [comment]
Yeah, it seems so - it's not actionable on our side then. Closing this.

Thanks @chuntley for checking!
