### ISSUE TITLE
Right-click paste in IE11 does not trigger resize

### ISSUE THREAD

**Issue by ratenbuuren** [andreypopp/react-textarea-autosize#179]
**Steps to reproduce:**

open https://andreypopp.github.io/react-textarea-autosize/ in Internet Explorer (used 11)
Right-click and paste multiple lines of code in a textarea

**Expected results:**
Textarea height resizes after the paste
![image](https://user-images.githubusercontent.com/6205060/30642042-7df27dc2-9e09-11e7-8bb7-b5407e8ec7a9.png)

**Actual results:**
No resize
![image](https://user-images.githubusercontent.com/6205060/30642024-6c8c8032-9e09-11e7-96e1-1b324f3fb4c7.png)

I have seen in other projects that an onInput stead of onChange would solve this issue, since IE picks it up as an update of the element.

**Comment by ratenbuuren** [comment]
Using onInput works, maybe update the examples 👍

**Comment by Andarist** [comment]
Actually it might be a React's bug with not calling `onChange` in such scenario for IE. Would need further investigation though on the React's side
