### ISSUE TITLE
update react's peer dependency version

### ISSUE THREAD

**Issue by danielberndt** [andreypopp/react-textarea-autosize#18]
since react v0.13.1 is out now, this module can't be installed due to the `peerDependencies requirements`. An update would be appreciated a lot (and judging by the 0.13 change log, no breaking changes should have happened here either)

Cheers!

**Comment by KyleAMathews** [comment]
It should install just fine. The peerDependency is set to anything above 0.10.0 — https://github.com/andreypopp/react-textarea-autosize/blob/c1d1d858c126f0751e470de9eb5d212565084d5d/package.json#L24
