### ISSUE TITLE
Option for min-height? 

### ISSUE THREAD

**Issue by christoph-fricke** [andreypopp/react-textarea-autosize#186]
@andreypopp Is there an option to set the `min-height` for this component? I have seen on the example website that you can set the `max-height`. However I am not able to do it in the same way with `min-height`.

**Comment by Andarist** [comment]
Hm, what's the problem with `min-height`? Ive checked it by changing `maxHeight` to `minHeight` in mentioned demo and it seems to work fine.

**Comment by christoph-fricke** [comment]
@Andarist In my case the component calculates it's height with 26px. That is usually fine but I have a rare case where a scrollbar appears on the side even when it is not needed... Hiding the scrollbar completely is no option since there is a need for it after a the max-height.
My plan is to set the min calculation height to 30px with the hope to prevent the unwanted scrollbar.
Normally it only appears after the height of the component reaches the max-height.

**Comment by Andarist** [comment]
I would suspect the scrollbar is showing up for some reason and that reason would have to be found to fix it. Can you share a sample repository and steps for reproduction?

**Comment by christoph-fricke** [comment]
@Andarist Sorry but I can't show a sample repository and I don't have steps for reproduction since this bug is so rare that we are not sure how it gets caused. But thanks for help... I will keep an eye on this...
