### ISSUE TITLE
inputRef prop type should be `object`, not `func`

### ISSUE THREAD

**Issue by CLL80** [andreypopp/react-textarea-autosize#188]
It's not recommended to use arrow functions in render because a new instance of the function is created for each render. Therefore, we should define our refs as a class property like this:

```js
class SomeComponentName extends Component {
  inputRef = ref => (this.inputRef = ref)
```

And reference them in the render like this:

```js
  <Textarea
    inputRef={this.inputRef}
```

This means `this.inputRef` is an object, not a function like it would be if it were defined in the render, like this:
```js
<Textarea
  inputRef={ref => (this.inputRef = ref)}
 
```

Because of this, you'll see this error:

```js
Failed prop type: Invalid prop `inputRef` of type `object` supplied to `TextareaAutosize`, expected `function`.
```

So, `inputRef` should have an `object` propType, not `func`. Alternatively, we could allow for either an object or function for those that wish to leave it in `render`.

**Comment by Andarist** [comment]
```
// example A
class SomeComponentName extends Component {
  inputRef = ref => (this.inputRef = ref)

// example B
<Textarea
  inputRef={ref => (this.inputRef = ref)}
```

In both example what you pass to `inputRef` is a **function** (class property can be of any type, but in this case you initialize it as function). The propType is correct. You are definitely passing something else and you get an error because of that.

**Comment by CLL80** [comment]
Thanks, @Andarist. You're right—this has to do with something in my project, but I haven't narrowed it down yet. I'll update this when I find it.

**Comment by CLL80** [comment]
I had accidentally used `PropTypes.boolean` for another prop instead of `PropTypes.bool`. What's strange is the error showed for the `inputRef` prop instead of the prop with the invalid type. Sorry for the trouble.

**Comment by CLL80** [comment]
Actually, that wasn't it. It was because the `inputRef` class property had the same name as what I was assigning the ref to—`this.inputRef`. changing `inputRef = ref => (this.inputRef = ref)` to `storeInputRef = ref => (this.inputRef = ref)` takes care of it. What threw me off was that even with the name matching the ref, the errors only showed up when I was using `@storybook/addon-knobs`.
