### ISSUE TITLE
Import problems with SSR

### ISSUE THREAD

**Issue by noamalffasy** [andreypopp/react-textarea-autosize#189]
I use next.js and I have a specific problem with the textarea **only** when I use it with SSR.

Here's the code: 
```
import Textarea from "react-textarea-autosize";
.
.
.
.
<Textarea />
```

and here's the error:
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's def
ined in, or you might have mixed up default and named imports.
```

**Comment by Andarist** [comment]
I suspect you have used the component somehow in a wrong way or your project is misconfigured.

Without sample repository on which the problem could be recreated I'm unfortunately afraid that I won't be able to help you any further. If you provide such repository I might take a look, closing for now as no actionable without repro.

**Comment by noamalffasy** [comment]
Hey @Andarist,
Sorry it took some time,
[Here's a repository](https://github.com/noamalffasy/react-textarea-autosize-issue) that shows the issue.

**Comment by Andarist** [comment]
Could u try with `react-textarea-autosize@6.0.0-0`? I've just published it with a fix, if you confirm that it works I'll publish 6.0 as latest

**Comment by noamalffasy** [comment]
Hi @Andarist,
It works!
Thanks!
