### ISSUE TITLE
Problems with autosize when use newline symbol '\n'

### ISSUE THREAD

**Issue by soldat27** [andreypopp/react-textarea-autosize#193]
I use next code: 

`let value = "Lorem Ipsum is simply dummy text of the pzrzidsnting a - _________________________________________________Lorem Ipsum is simply dummy __________ \n" +
            "Lorem Ipsum is simply dummy text of the printing a - _________________________________________________Lorem Ipsum is simply dummy __________";`

        return (
                <div className="">
                    <Textarea defaultValue={value}
                    />
                </div>
        );

But I have problem with autosize. I see scroll. If i remove '\n' it's works fine.

![11111111](https://user-images.githubusercontent.com/4384731/36894947-2d8c8c84-1e1e-11e8-9905-5708073b4451.jpg)

**Comment by Andarist** [comment]
It might be some browser quick. Could u specify on what browser do u see this behaviour? Everything is ok for me in latest Chrome - https://codesandbox.io/s/8y7k93pzq0

**Comment by soldat27** [comment]
I use the latest Chrome version(64.0.3282.186)
Hm, i don't have problem at your example. But problem remained in main project..

**Comment by Andarist** [comment]
This might be connected to some styling you are using, hard to judge without repro case. Could u try to extract one from your project?

**Comment by Andarist** [comment]
Closing because original author did not provide enough information to handle this.
