### ISSUE TITLE
React 16.3.0 componentWillReceiveProps warning

### ISSUE THREAD

**Issue by jxbetancourt** [andreypopp/react-textarea-autosize#197]
Running app using the React.StrictMode component reveals this warning in console:

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: TextareaAutosize

**Comment by Andarist** [comment]
I'll explore preparing a new version using https://github.com/reactjs/react-lifecycles-compat .

**Comment by Andarist** [comment]
@jxbetancourt & @Hypnosphi I'd appreciate you testing (along with me ofc) new version - `react-textarea-autosize@next`.

I've moved resize scheduling from `componentWillReceiveProps` to `componentDidUpdate` and didn't found any problem with it yet.

**Comment by josefbetancourt** [comment]
@Andarist Will test.

**Comment by josefbetancourt** [comment]
@Andarist Tested.  Great!  Thanks for excellent OSS efforts.

**Comment by Andarist** [comment]
Published as `latest`
