### ISSUE TITLE
Add option for empty height

### ISSUE THREAD

**Issue by daedelus-j** [andreypopp/react-textarea-autosize#20]

**Comment by KyleAMathews** [comment]
All props are passed to the underlying textarea so you can do whatever you'd normally in HTML e.g. `<TextareaAutosize rows=0/>`

I have to ask though — why would you want a textarea with no height? Or did you mean you want the textarea to start out looking like at text input so only be one row tall?

**Comment by daedelus-j** [comment]
@KyleAMathews thanks for the quick reply! 

Yes, the latter. The height of the textarea when the text field is empty (or, I suppose, one row tall).

**Comment by KyleAMathews** [comment]
Great! :)

**Comment by daedelus-j** [comment]
@KyleAMathews ah I was hoping for the ability to add the height in pixels?

**Comment by KyleAMathews** [comment]
You can use the style prop for that.

**Comment by daedelus-j** [comment]
@KyleAMathews ah ok, inline styles?

```
var Textarea = require('react-textarea-autosize');

React.renderComponent(
  <div>
    <Textarea
      style='height: 40px; display: inline-block'>
    </Textarea>
  </div>,
  document.body);

```

**Comment by KyleAMathews** [comment]
Yeah exactly.

**Comment by daedelus-j** [comment]
@KyleAMathews can I add this to the docs?

**Comment by KyleAMathews** [comment]
That'd be great, thanks!
