### ISSUE TITLE
What does useCacheForDOMMeasurements do?

### ISSUE THREAD

**Issue by joetidee** [andreypopp/react-textarea-autosize#201]
The documentation is a little light. Any chance of adding this in?

**Comment by Andarist** [comment]
I would gladly accept a PR for this. Basically what this component does is that it takes ref to your textarea, copies some styles onto hidden global textarea, measures the height and setState with it so your textarea rerenders with correct height. This prop tells us that it is safe to cache most of those measurements, that you won't change styles that affect it (i.e. `line-height`) between renders.

**Comment by Andarist** [comment]
Benefit is performance optimization. When not to use it? If your textarea change its styles after a mount.
