### ISSUE TITLE
Height of textarea not correct when initially rendered.

### ISSUE THREAD

**Issue by joetidee** [andreypopp/react-textarea-autosize#202]
When I have a few lines of text in the textarea, sometimes the textarea will show a scrollbar (with no scroll handle).

**Comment by joetidee** [comment]
Seems as though I have to add `overflow-y: hidden` to the style of the <Textarea> component.

**Comment by Andarist** [comment]
Is your issue fixed? Could u post a codesandbox with reproduction case?

**Comment by joetidee** [comment]
Yes fixed.
