### ISSUE TITLE
Past problem

### ISSUE THREAD

**Issue by Dictory** [andreypopp/react-textarea-autosize#203]
Hello.
`react-textareat-autosize` has problem with past some text in textarea without `maxHeight` or `maxRow`.
For reproduce:
1) go to demo, scroll to controlled mode
2) change textarea width
3) past any text, for example
```
Want to submit an issue to andreypopp/react-textarea-autosize?
If you have a bug or an idea, browse the open issues before opening a new one. You can also take a look at the Open Source Guide.
```

**Comment by Andarist** [comment]
Could u describe ur problem in more details? Maybe you could record a video show casing it?

**Comment by Dictory** [comment]
[gif for show](https://drive.google.com/file/d/15Jv5Z_4zjgVpoy3v_Y-k03j6oOh7ilL9/view?usp=sharing)

**Comment by Andarist** [comment]
Isnt this just caused because this example uses `useCacheForDOMMeasurements` prop?

**Comment by Andarist** [comment]
Closing because original author did not provide enough information to handle this.
