### ISSUE TITLE
not updating with font size change

### ISSUE THREAD

**Issue by arnaudambro** [andreypopp/react-textarea-autosize#204]
Hi there,
Thanks for your lib, it's cool.

However I have a bug in my app : I actually am allowed to change the font-size of the text, and when the font-size has changed, it's not resizing the component.

How could I do ? Even a hack would be sufficient for me.

Thanks !
Cheers,
Arnaud

**Comment by Andarist** [comment]
Could u prepare a repro case for this on something like codesandbox.io ?

**Comment by Andarist** [comment]
Closing because original author did not provide enough information to handle this.
