### ISSUE TITLE
"POLYFILL.IO REQUIRES URGENT UPGRADE"

### ISSUE THREAD

**Issue by 1j01** [andreypopp/react-textarea-autosize#21]
At http://andreypopp.github.io/react-textarea-autosize/ in the console it says `POLYFILL.IO REQUIRES URGENT UPGRADE.  Polyfills will stop serving soon from this legacy version of the service.  Please upgrade to the new service available at cdn.polyfill.io, which also offers vastly superior, better tested polyfills covering a wider range of browser features, along with faster performance and many other improvements.`
See http://cdn.polyfill.io/v1/docs/

**Comment by andreypopp** [comment]
I just deleted it for now.
