### ISSUE TITLE
Ref missing?

### ISSUE THREAD

**Issue by zslabs** [andreypopp/react-textarea-autosize#212]
👋 

Didn't something change with how we can attach a ref to this package? I noticed in `6.1.0` that I can attach a ref, but in `7.0.3` it can't find the element.

**Comment by Andarist** [comment]
Could you share your code? No idea how do you try to attach it.

**Comment by zslabs** [comment]
Hey,
Thanks for the quick response. I created a quick demo on https://codesandbox.io/s/4r817movz9

If you look in `src/index.js` I've been able to use `__rootDOMNode` but it doesn't appear to be available in recent versions. Is there a better way to grab the actual DOM behind this package? Thanks!

**Comment by Andarist** [comment]
You just have to use `<Textarea inputRef={el => (this.textarea = el)} />`. `_rootDOMNode` was never part of the public API (which is denoted by `_`, common convention for private things) and it got renamed to `_ref` in v7.

Either way, please just use `inputRef` instead of `ref` for this component.

**Comment by zslabs** [comment]
Great, thanks!
