### ISSUE TITLE
props not documented

### ISSUE THREAD

**Issue by danedavid** [andreypopp/react-textarea-autosize#227]
The valid props that could be given ( like `minRows` ) is not documented on the README as well as on the NPM page. It can be seen only by goint to the examples. If okay, I would be glad to add the documentation myself.

**Comment by Andarist** [comment]
Sure, it would be great to add a listing of all supported "special props" - https://github.com/andreypopp/react-textarea-autosize/blob/010cadfbcd85b1e1163a46d10afa2fbf06a21c79/src/index.js#L14-L23

And additionally we should mention that we accept any other prop that `<textarea/>` is accepting.
