### ISSUE TITLE
`rows` attribute not respected

### ISSUE THREAD

**Issue by KyleAMathews** [andreypopp/react-textarea-autosize#23]
`<Textarea rows=4/>` gets set to a height of one row.

Haven't grokked the new code yet sufficiently to see how to fix this. I'll get to this next week unless one of you want to get to it first.

**Comment by andreypopp** [comment]
I think setting `minHeight` would work for setting an initial and minimal height.

**Comment by KyleAMathews** [comment]
Sure but `minHeight` isn't as simple to use as `rows` uses the `line-height` automatically whereas with `min-height` you have to calculate this.

**Comment by andreypopp** [comment]
Fair enough! Released in `2.1.0`.

**Comment by andreypopp** [comment]
Actually that doesn't solve the issue when we don't have newlines in value and it is just wrapped to the next line automatically by browser.

**Comment by KyleAMathews** [comment]
Thanks!
