### ISSUE TITLE
Last Character is missing in value

### ISSUE THREAD

**Issue by MistrySaurabh** [andreypopp/react-textarea-autosize#230]
I have tried below code and console log state value , it is missing last character in value .

```
import React, {Component} from 'react';
import Textarea from 'react-textarea-autosize';

export default class TextareaAutosize extends Component {
    constructor(){
        super();
        this.state={
            value:''
        }
    }
    render() {
        return (
            <div>
                <Textarea
                    defaultValue=''
                    onChange={e =>{
                        this.setState({value: e.target.value});
                        console.log('value==',this.state.value)
                    }}
                    onHeightChange={(height, instance) => console.log('height=='+height, 'instance=='+instance.rowCount)}
                />
            </div>
        );
    }
}
```
See here , last character O is missing 

<img width="185" alt="screen shot 2018-12-27 at 17 27 11" src="https://user-images.githubusercontent.com/16002832/50479465-bf747600-09fc-11e9-997f-639b79741d75.png">

**Comment by Andarist** [comment]
React's state is asynchronous - you can't read it just after setting it. More resources:
- https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous
- https://github.com/facebook/react/issues/11527#issuecomment-360199710
