### ISSUE TITLE
Value prop: Type 'number' is not assignable to type 'string | undefined'

### ISSUE THREAD

**Issue by Rahul-Sagore** [andreypopp/react-textarea-autosize#238]
I am using typescript in my project. 

Getting this error `Type 'number' is not assignable to type 'string | undefined'`

![Screen Shot 2019-04-03 at 3 05 48 PM](https://user-images.githubusercontent.com/3587851/55468974-26b84c80-5622-11e9-8f49-a1d1b119873d.png)

My code:

```
     <TextareaAutoSize
          inputRef={ this.textarea }
          className={ className }
          placeholder={ placeholder }
          value="Hello"
          disabled={ disabled }
     />
```

**Comment by Andarist** [comment]
TS typings are not defined in this repo (yet) - I suspect they are coming from DefinitelyTypes repo and you should report it over there.
