### ISSUE TITLE
Something wrong when I use this component

### ISSUE THREAD

**Issue by mizhdi** [andreypopp/react-textarea-autosize#24]
![image](https://cloud.githubusercontent.com/assets/3582887/7448301/ba9da036-f248-11e4-8f84-748ca9a0664f.png)

**Comment by andreypopp** [comment]
Can you show the traceback? It seems like it doesn't work with react-hot-loader?

**Comment by mizhdi** [comment]
![image](https://cloud.githubusercontent.com/assets/3582887/7470825/e442c1ea-f352-11e4-83a9-acf4604b76dc.png)

**Comment by andreypopp** [comment]
cc @gaearon any ideas?

**Comment by gaearon** [comment]
I'll take a look later today.

**Comment by mizhdi** [comment]
Thanks!

**Comment by gaearon** [comment]
Please could you create a Github project reproducing the problem.

**Comment by andreypopp** [comment]
@mizhdi any feedback on this?

**Comment by mizhdi** [comment]
no, just ues browserify

**Comment by andreypopp** [comment]
@mizhdi can you post output from running `npm ls` in the project directory?

**Comment by alexfedoseev** [comment]
Just faced similar (?) issue:

```
Uncaught Error: Invariant Violation: Component (with keys: props,context,state,_onChange,_resizeComponent,refs,_reactInternalInstance) contains `render` method but is not mounted in the DOM
invariant @ invariant.js:42
findDOMNode @ findDOMNode.js:54
_resizeComponent @ TextareaAutosize.js:96
```

I forgot that it's not actually DOM element and did this:

```javascript
<Textarea ref="content" />

let content = React.findDOMNode(this.refs.content).value.trim();
```

Not sure if this related to current issue, but anyway: how should I get the value of `textarea` DOM node inside wrapper component?

**Comment by andreypopp** [comment]
Interesting... seems like one of the lifecycles methods (componentDidMount/componentWillReceiveProps) is called when component isn't in the DOM.

@alexfedoseev are you also using react-hot-loader?

**Comment by andreypopp** [comment]
@alexfedoseev I'm not sure traceback provided by your is related to code snippet as 3rd frame points to `findDOMNode` within the `TextareaAutosize` component.

**Comment by alexfedoseev** [comment]
>are you also using react-hot-loader?
Nope.

>I'm not sure traceback provided by your is related to code snippet as 3rd frame points to findDOMNode within the TextareaAutosize component.
You're right, it's not related. It still throws the same error when I'm not placing ref on it.

**Comment by alexfedoseev** [comment]
I'm using it inside `FlummoxComponent`:

```javascript
<FlummoxComponent connectToStores={'store'}>
  <Form {...this.props} />
</FlummoxComponent>
```

When I place `<Form />` component to routes without `flummox` wrapper — error is gone.

**Comment by andreypopp** [comment]
@alexfedoseev can I see the complete traceback?

**Comment by alexfedoseev** [comment]
I did a bunch of stuff yesterday and now I can't reproduce it. It's still inside `FlummoxComponent`, but error is gone.
