### ISSUE TITLE
Component broken in Safari

### ISSUE THREAD

**Issue by ewal** [andreypopp/react-textarea-autosize#25]
Referring to the demo page. Tested in Safari 8.0.5 in OSX Yosemite10.10.3.

**Comment by andreypopp** [comment]
It seems it needs `babel/polyfill` module because of `autobind-decorator`,

**Comment by KyleAMathews** [comment]
@andreypopp why not just require the polyfill in the module itself?

**Comment by KyleAMathews** [comment]
nvm, just saw https://github.com/andreypopp/react-textarea-autosize/commit/9b652f7cbf0585b9f75ca7ed6167fdda4e6c240f

This is even better :)

**Comment by andreypopp** [comment]
@KyleAMathews I just removed `autobind-decorator` :-)

**Comment by andreypopp** [comment]
Fixed in 2.0.1

**Comment by ewal** [comment]
:+1:
