### ISSUE TITLE
TypeError: hiddenTextarea.setAttribute is not a function

### ISSUE THREAD

**Issue by piotrblasiak** [andreypopp/react-textarea-autosize#253]
7.1.1 gives this error:

.../node_modules/react-textarea-autosize/dist/react-textarea-autosize.cjs.js:31
hiddenTextarea.setAttribute('tab-index', '-1');
               ^
TypeError: hiddenTextarea.setAttribute is not a function

**Comment by Andarist** [comment]
Please stick to 7.1.0 - im on the road, will fix it when i get to my destination. Do u see this error in the browser or while SSRing?

**Comment by piotrblasiak** [comment]
Yep sticking to 7.1.0. While SSR.

Piotr

**Comment by piotrblasiak** [comment]
That was quick. Thank you!
