### ISSUE TITLE
Publish typescript definitions with package

### ISSUE THREAD

**Issue by joshiste** [andreypopp/react-textarea-autosize#255]
currently the `@types/react-textarea-autosize` is not up to date.

Since the component is written in typescript, you should publish the `d.ts` with this package and add a `"types"` entry to the package.json

**Comment by Andarist** [comment]
This component is not written in TypeScript (yet). I plan to rewrite it to TS and hooks but couldnt find the time to do it just yet

**Comment by joshiste** [comment]
Hmmm looks like I was looking at the wrong code from react-autosize-textarea. nevermind!
