### ISSUE TITLE
Use goog textarea

### ISSUE THREAD

**Issue by steida** [andreypopp/react-textarea-autosize#28]
This is the only one reliable growing textarea I know.

https://github.com/google/closure-library/blob/master/closure/goog/ui/textarea.js

**Comment by nikgraf** [comment]
@steida Did it not work out for you? What issues did you encounter?

**Comment by steida** [comment]
Just checking open issue was enough. Closure implementation is stable for years.

**Comment by steida** [comment]
I had some issues but now it seems it should work. Ok, I will try it. Sorry for FUD :-)

**Comment by nikgraf** [comment]
No worries, let us konw once you run into any issues.
