### ISSUE TITLE
Uncaught Error: Invariant Violation

### ISSUE THREAD

**Issue by alexfedoseev** [andreypopp/react-textarea-autosize#30]
Further to #24 

Here is the sample app to reproduce an issue: https://github.com/alexfedoseev/flummox-cuts
Clone repo && `npm install` && `npm start`.

If you'll click on any tag link in the post list, there will be an error in console:

![image](https://cloud.githubusercontent.com/assets/4244251/7907131/26107676-083e-11e5-807b-4c147598bb0f.png)

**Comment by andreypopp** [comment]
Released 2.2.3 with fixes by @eugene1g, it should fix this issue.

**Comment by alexfedoseev** [comment]
@andreypopp @eugene1g Everything's ok, thanks!
