### ISSUE TITLE
Compatibility with react-bootstrap?

### ISSUE THREAD

**Issue by dlong500** [andreypopp/react-textarea-autosize#33]
I don't know the best way to approach this, so I'm just throwing it out there.  If I'm already using react-bootstrap (http://react-bootstrap.github.io), what is the best way to approach using your code as well (given that react-bootstrap has their own textarea component)?

Just thought I'd ask in case anyone has already faced the same issue.

**Comment by andreypopp** [comment]
Hi, it seems like React Bootstrap doesn't allow to inject custom component to render as `<Input />` so it's not possible to pass it `<TextareaAutosize />`.

But you can style `<TextareaAutosize />` with Bootstrap CSS classes so it will integrate nicely with the framework (to be honest I'm not sure why `<Input />` component is useful in React Bootstrap).

Closing this, feel free to reopen if you think there's anything actionable left on our part.

**Comment by athimannil** [comment]
@andreypopp The auto height works fine but unfortunately textarea doesn't give auto when for the initial stage when it has`form-control` class 
```
<TextareaAutosize
  minRows={3}
  value={value}
  onChange={handleChange}
  className={
    isDarkTheme
      ? 'form-control bg-dark text-white'
      : 'form-control bg-white text-dark'
  }
/>
```
