### ISSUE TITLE
Invoke callback when textarea changes it's height.

### ISSUE THREAD

**Issue by Andreyco** [andreypopp/react-textarea-autosize#36]
It would be great if there is an option to pass callback which is invoked when text area changes it's height.

**Comment by andreypopp** [comment]
Reasonable, want to send a pull request?

**Comment by Andreyco** [comment]
yeah, working on it ;)

**Comment by Andreyco** [comment]
Unfortunately, cannot run from source. Building with Webpack.

```
Uncaught Error: Invariant Violation: Component (with keys: ) contains `render` method but is not mounted in the DOM
```
