### ISSUE TITLE
Wrong calculation of Height

### ISSUE THREAD

**Issue by a6hi5h3k** [andreypopp/react-textarea-autosize#39]
The method `calculateNodeHeight()` calculates height for one row using `hiddenTextarea.scrollHeight`. 
The property will also include any padding that is applied. And when to calculate height for *n* rows, the value is multiplied by *n*, and as a result the padding gets multiplied as many times.
Is this intended?

**Comment by danyalaytekin** [comment]
Why was this closed?  I still see padding issues.

**Comment by Andarist** [comment]
@danyalaytekin Please prepare a codesandbox.io demo showcasing your problem. Without it I won't be able to help you.
