### ISSUE TITLE
Make component pure

### ISSUE THREAD

**Issue by steida** [andreypopp/react-textarea-autosize#41]
Use this https://github.com/gaearon/react-pure-render, because componentWillReceiveProps and componentDidUpdate are pretty expensive.

Check este implementation https://github.com/este/este/blob/a729f53afd671333cb1932f39ca8682633bce4ad/src/client/components/component.react.js#L14

**Comment by andreypopp** [comment]
I'd rather defer this kind of optimisations to an app level.

**Comment by steida** [comment]
No reason to defer. Just add shouldComponentUpdate with shallow check for props, done.

**Comment by andreypopp** [comment]
@steida we at least should add shallow checking for `style` prop specifically as it would allow us to cover more cases when we need to bail out of reconciliation.

**Comment by andreypopp** [comment]
Closing as I think it would be better to apply those optimizations with more knowledge from the usage side.
