### ISSUE TITLE
transfer className property to textarea

### ISSUE THREAD

**Issue by khakulov** [andreypopp/react-textarea-autosize#50]
or generally transfer all possible props to real textarea component.

```javascript
import React from "'react";
import Textarea from "'react-textarea-autosize";

React.renderComponent(
  <Textarea onFocus={this.handleFocus} onBlur={this.handleBlur} autofocus></Textarea>,
  document.body
)
```

**Comment by kun-zhou** [comment]
I agree. Why closed?

**Comment by Andarist** [comment]
@kun-zhou `props` are passed through to the underlaying `textarea`. You can see it [here](https://github.com/andreypopp/react-textarea-autosize/blob/f9320de2058406258bae53ec4158e7064ca0b5a9/src/index.js#L83)

**Comment by kun-zhou** [comment]
@Andarist Thank you! Sorry for being an idiot and not reading the code.
