### ISSUE TITLE
What is the use case for `onHeightChange` callback?

### ISSUE THREAD

**Issue by necolas** [andreypopp/react-textarea-autosize#54]
(Context: I am playing around with using this in https://github.com/necolas/react-native-web/)

What do you see as the use case for this? The callback takes a `height`, which seems to be the CSS height (respects `border-box`) rather than the layout height of the element.

So to implement `onLayout` I need to re-query the DOM anyway, to get the outer height/width/offset. But one thing I cannot do easily is infer the number of rows. That might be quite useful to pass to the callback.

**Comment by andreypopp** [comment]
Sounds reasonable. i'd accept a PR for that.

**Comment by necolas** [comment]
I'll probably drop this dependency as it's not actively developed or tested, so won't get around to adding this change.
