### ISSUE TITLE
How to reset textarea's height?

### ISSUE THREAD

**Issue by Qrysto** [andreypopp/react-textarea-autosize#59]
How can I reset the textarea height, for example when user press Enter and we need to clear the textarea and reset its height accordingly?

**Comment by andreypopp** [comment]
Doesn't setting `value=""` work?

**Comment by Qrysto** [comment]
Probably it does, but how about the case that I don't want a controlled `value`?

**Comment by andreypopp** [comment]
How do you update its value then?

**Comment by Qrysto** [comment]
I don't, I just use ref to get its value when user submits, then reset its value to '' (empty string)

**Comment by jmcrthrs** [comment]
@Qrysto I know this is an old one, but if any one else comes looking for an answer:

Because the input is uncontrolled, you need to reset the height manually via the DOM style property:

`
<Textarea 
    inputRef={(textarea) => { this.textarea = textarea; }}
    ...
</Textarea>
`

`this.textarea.style.height = '31px'`

Assuming your

**Comment by Andarist** [comment]
@jmcrthrs if you implement custom logic with i.e enter clearing the textarea's value **you should control it** - this is not an advise for this particular case, but rather a general React one. You should lift your state and control it when the need arises. Manipulating DOM is an anti-pattern and should be avoided.

**Comment by insivika** [comment]
I'm setting the body to an empty string however it does not reset the height

![Screen Shot 2021-08-05 at 1 29 52 PM](https://user-images.githubusercontent.com/33808429/128402498-21b45750-13a3-47cf-9222-757202ff6025.png)

**Comment by Andarist** [comment]
Im afraid that u would have to provide a full repro case for this situation before I could dive into this

**Comment by insivika** [comment]
Hi @Andarist thanks for the quick respond, I put together an example on codesandbox and my issue is actually related to the keydown event. When pressing enter, I'm sending a message (omitted in this example) and resetting the body however I'm still left with a line break.

https://codesandbox.io/s/great-wu-c4kgc?file=/src/App.js

**Comment by insivika** [comment]
Hi @Andarist did you have a chance to look into this?

**Comment by Andarist** [comment]
You should use `event.preventDefault()` to avoid that newline being entered: https://codesandbox.io/s/interesting-easley-m5960?file=/src/App.js

**Comment by insivika** [comment]
Thanks so much @Andarist !
