### ISSUE TITLE
"Cannot read property 'value' of undefined" when re-exported + hot-loader

### ISSUE THREAD

**Issue by alexeygolev** [andreypopp/react-textarea-autosize#63]
I have one module where I just collect all the components I need and then reexport them like so
```js
export TextArea from 'react-textarea-autosize'
```
as soon as I try to import it react-textarea-autosize throws. It tries to get value but it's obviously not mounted yet.
I assume I'm doing something weird and react-hot-loader is not enjoying it.
Ideas? @gaearon
![screen shot 2015-10-08 at 22 44 47](https://cloud.githubusercontent.com/assets/1342730/10380842/45c03f2a-6e0e-11e5-99e4-23bf72be05d9.png)

**Comment by andreypopp** [comment]
AFAIK react-hot-loader 1.x doesn't handle property descriptors correctly.

Try `react-hot-loader@2.0.0-alpha-4` or better [React Transform based HMR](https://github.com/gaearon/react-transform-boilerplate) (this is the successor of RHL by the same author).

I believe this should fix the problem. If not, please reopen the issue.
