### ISSUE TITLE
event.keycode issue. 

### ISSUE THREAD

**Issue by martingg88** [andreypopp/react-textarea-autosize#67]
how to handle event.keycode at onChange?

if i try to added onKeyDown event and then onChange will not be fired. any idea?

**Comment by sorenbs** [comment]
I have a similar issue.

I want to submit the form when the user clicks the return key, so I assumed I could check the key or keyCode property on the onKeyDown handler. But all properties are null:

key: null
keyCode: null
...

**Comment by tzapu** [comment]
hi guys, i can listen for keys and process/handle return presses with a code like the following
```
<Textarea
                        ref={(c) => this._input = c}
                        rows={1}
                        maxRows={6}
                        onKeyPress={this.handleKeyPress}
                        placeholder="Enter your question here"
                        style={{
                          width: '100%',
                          border: 'none',
                          resize: 'none',
                          outline: 'none',
                          boxSizing: 'border-box',
                          paddingLeft: '10px',
                          paddingRight: '60px',
                          paddingTop: '10px',
                          paddingBottom: '10px',
                        }}
                      >
</Textarea>

  handleKeyPress = (e) => {
    if (e.key === 'Enter') {
      this._input.value = '';
      e.preventDefault();
    } else {
...
      }, 3000);
    }
  }
```

**Comment by Andarist** [comment]
Same here, no problems for quite some time with `onKeyDown`. Going to close this as it seems already resolved.

**Comment by nadzimo** [comment]
Having also a problem.  
The `onChange` prop is passing an event object that doesn't seem to have a `key` attribute. `e.key` is null. Any progress on this?

**Comment by Andarist** [comment]
This component doesnt do anything weird with attached event listeners, so your problem must be JS/DOM-related

**Comment by vibecode** [comment]
I had no luck of using e.keyCode because currently it returns 0 with all keys for whatever reason.
