### ISSUE TITLE
Performance issues on pages with lots of non-related components (if an id isn't given)

### ISSUE THREAD

**Issue by nemo** [andreypopp/react-textarea-autosize#73]
Hey folks,

We were experincing a lot of performance issues with this component on large pages (pages with a lot of other components, specifically). This is after we started using `useCacheForDOMMeasurements`.

After looking at the code [here](https://github.com/andreypopp/react-textarea-autosize/blob/master/src/calculateNodeHeight.js#L95) – it looks like if there's no `id` given, the component attempts to find the node using `react-id`, which is what was slowing it down.

The solution for us was to just assign an `id` (easy!) – but I thought it was worth writing up something here and making asking you to include it as part of the docs/README.

Cheers!

**Comment by KyleAMathews** [comment]
Or just setting an id by default?

**Comment by nemo** [comment]
Actually – I was on the wrong page when I tested the performance again (one with less components on it).

Even with an `id` it's still slow (though, defintely slighly less slow). Not sure what else to do.

**Comment by jdalton** [comment]
Hi @nemo!

Feel free to ping back with a reduced repro.
