### ISSUE TITLE
Not working in ie11 - wrong height

### ISSUE THREAD

**Issue by vavdav** [andreypopp/react-textarea-autosize#74]
Hello,
I have problem with textarea height in ie11.  
Problem is on this line:
https://github.com/andreypopp/react-textarea-autosize/blob/master/src/calculateNodeHeight.js#L73

IE11 is returning 2. Another browser is returning 21. 

Please how to solve this problem?

**Comment by mitchcunha** [comment]
I saw something similar with IE11, but the right height was being calculated, but the state wasn't being set correctly.

The temporary fix that I found was changing the setState call in TextareaAutosize.js on line 128 to this:

this.setState(_calculateNodeHeight2'default');

It had some other || parameters, but that was causing some bugginess in IE11. Hope this helps, or if you know about this already, please let me know!

Best,

Kevin

**Comment by CoderK** [comment]
You can find the solution in the link below.
[https://github.com/andreypopp/react-textarea-autosize/tree/fix-ie-height-calculation]

**Comment by vavdav** [comment]
It is not working. It is happening when I have already some text inside textarea. I am using version 3.2.0

**Comment by vavdav** [comment]
It is not working with '\uFEFF' but with 'x' it is working

**Comment by just-paja** [comment]
Why don't we use '\u00A0' aka NBSP aka ' '?

**Comment by dshorowitz** [comment]
I just came across this problem as well. In fact, you can see the issue by going to the demo page (http://andreypopp.github.io/react-textarea-autosize/). In IE11, as you start typing in the blank textarea, its height grows too early. Anyone have a fix? Thanks :)

**Comment by jdalton** [comment]
Fixed https://github.com/andreypopp/react-textarea-autosize/issues/55#issuecomment-242201491.
