### ISSUE TITLE
maxlength attribute

### ISSUE THREAD

**Issue by joerodrig** [andreypopp/react-textarea-autosize#83]
It would be nice if we could set a max length

**Comment by steida** [comment]
It supports. Use `maxLength="4"`.

I wonder what happen to library author that he does not respond.

**Comment by KyleAMathews** [comment]
Perhaps on vacation from answering requests for help :-)

**Comment by oyeanuj** [comment]
@Andarist Came here looking for the same - thoughts on supporting max length?

**Comment by Andarist** [comment]
@oyeanuj It's supported - every prop not related to autosize gets passed down to the inner DOM textarea.
