### ISSUE TITLE
Getting HTML element ref

### ISSUE THREAD

**Issue by anthonator** [andreypopp/react-textarea-autosize#91]
Is it possible to get the element ref off of a textarea?

When doing something like this:

``` js
<TextArea ref='content' />
```

I'd expect to be able to do something like this:

``` js
this.refs.content.refs.content
```

which would get me the ref of the HTML element.

Unfortunately `this.refs.content.refs` returns an empty object.

In order to get the ref of the HTML element I have to do something like this:

``` js
this.refs.content._rootDOMNode
```

Let me know if I'm doing something wrong. Otherwise I'd like to figure out a way to get `refs` to work properly or make `_rootDOMNode` public.

**Comment by andreypopp** [comment]
It is not possible at the moment. I think the right way is to add a special prop called `inputRef` (or something like that name) which can be used to get a ref to underlying DOM element (see [callback refs](https://facebook.github.io/react/docs/more-about-refs.html#the-ref-callback-attribute)):

```
<TextareaAutosize inputRef={this._onInputRef} />
```

I'm open to a pull request with this functionality.

**Comment by jdalton** [comment]
Moved to #123.
