### ISSUE TITLE
Is there a way to set maxHeight: "20%"?

### ISSUE THREAD

**Issue by jef-sure** [andreypopp/react-textarea-autosize#94]
$subj. I can set maxHeight: 200, but not with procents.

**Comment by Andarist** [comment]
This one is quite tricky, but what is your use case? I think most people need this component for its `maxRows` feature

**Comment by Andarist** [comment]
Closing the issue, because its inactive. If you feel ur issue was not handled properly and u still need the feature, please post here and I reopen.
