### ISSUE TITLE
React 0.14 warning - style object previously mutated

### ISSUE THREAD

**Issue by rrcobb** [andreypopp/react-textarea-autosize#95]
Getting this error:
```Warning: `textarea` was passed a style object that has previously been mutated. Mutating `style` is deprecated. Consider cloning it beforehand. Check the `render` of `TextareaAutosize`. Previous style: {height: NaN}. Mutated style: {height: NaN}.```

Looks like #70 will solve it, but wanted to have a searchable issue in case anyone else is seeing this.

**Comment by herokun** [comment]
+1

**Comment by itszero** [comment]
Can confirm #70 does fix this, would be great if we can merge that.

**Comment by andreypopp** [comment]
Fixed in 4.0.2
