### ISSUE TITLE
Element type is invalid: expected a string on a simple instanciation. Documentation is incorrect on how to use this component

### ISSUE THREAD

**Issue by HadrienPierart** [andreypopp/react-textarea-autosize#98]
Working use is either : 

`var Textarea = require('react-textarea-autosize').default;`

or 

`import TextareaAutosize from 'react-textarea-autosize';`

The actual declaration in the documentation trigger an error :

> Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of  YourComponent

and

> Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of YourComponent

**Comment by CreepGin** [comment]
To clarify for anyone who got here searching for the error,  when importing you need to use `require(...).default` or the `import` default syntax.

Just using `var Textarea = require('react-textarea-autosize')` or `import * as Textarea from 'react-textarea-autosize' would give the errors above.
